<?xml version="1.0" encoding="utf-8"?>
<Project>
  <Import Project="..\..\src\Bolero.Build\Bolero.Build.props" />
  <PropertyGroup>
    <__BlazorSdkVersion Condition="'$(TargetFramework)' == 'net8.0'">8.0.0</__BlazorSdkVersion>
    <__BlazorSdkVersion Condition="'$(TargetFramework)' == 'net9.0'">9.0.0</__BlazorSdkVersion>
    <__BlazorSdkVersion Condition="'$(TargetFramework)' == 'net10.0'">10.0.0</__BlazorSdkVersion>
  </PropertyGroup>
  <Sdk Name="Microsoft.NET.Sdk.BlazorWebAssembly" Version="$(__BlazorSdkVersion)" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <BoleroTaskAssemblyPath>$(MSBuildThisFileDirectory)..\..\src\Bolero.Build\bin\$(Configuration)\netstandard2.0\Bolero.Build.dll</BoleroTaskAssemblyPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Html.fs" />
    <Compile Include="Templating.fs" />
    <Compile Include="Elmish.fs" />
    <Compile Include="Routing.fs" />
    <Compile Include="Remoting.fs" />
    <Compile Include="App.fs" />
    <Compile Include="Startup.fs" />
    <None Include="paket.references" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Bolero.Html\Bolero.Html.fsproj" />
    <ProjectReference Include="..\..\src\Bolero\Bolero.fsproj" />
  </ItemGroup>
  <Import Project="..\..\src\Bolero.Build\Bolero.Build.targets" />
  <Import Project="..\..\src\Bolero\Bolero.targets" />
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
