<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <__WebSdkVersion Condition="'$(TargetFramework)' == 'net8.0'">8.0.0</__WebSdkVersion>
    <__WebSdkVersion Condition="'$(TargetFramework)' == 'net9.0'">9.0.0</__WebSdkVersion>
    <__WebSdkVersion Condition="'$(TargetFramework)' == 'net10.0'">10.0.0</__WebSdkVersion>
  </PropertyGroup>
  <Sdk Name="Microsoft.NET.Sdk.Web" Version="$(__WebSdkVersion)" />
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Utility.fs" />
    <Compile Include="Startup.fs" />
    <Compile Include="Fixture.fs" />
    <Compile Include="Tests\Html.fs" />
    <Compile Include="Tests\Templating.fs" />
    <Compile Include="Tests\Elmish.fs" />
    <Compile Include="Tests\Routing.fs" />
    <Compile Include="Tests\Remoting.fs" />
    <Compile Include="Program.fs" />
    <None Include="paket.references" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Bolero\Bolero.fsproj" />
    <ProjectReference Include="..\..\src\Bolero.Server\Bolero.Server.fsproj" />
    <ProjectReference Include="..\Unit.Client\Unit.Client.fsproj" />
  </ItemGroup>
  <Target Name="_FixStaticWebAssetsFile" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)\Unit.staticwebassets.endpoints.json"
          DestinationFiles="$(OutputPath)\testhost.staticwebassets.endpoints.json"
          Condition="'$(TargetFramework)' != ''" />
    <Copy SourceFiles="$(OutputPath)\Unit.staticwebassets.runtime.json"
          DestinationFiles="$(OutputPath)\testhost.staticwebassets.runtime.json"
          Condition="'$(TargetFramework)' != ''" />
  </Target>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
